### ISSUE TITLE
Can't run tests from Xcode

### ISSUE THREAD

**Issue by pcbeard** [ctreffs/SwiftVulkan#3] opened 2021-09-11 23:04 UTC
If I open Package.swift in Xcode, then try to run the tests, I get the following error message:

2021-09-11 15:54:05.521079-0700 xctest[9114:4836983] The bundle “VulkanTests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2021-09-11 15:54:05.521257-0700 xctest[9114:4836983] (dlopen_preflight(/Users/beard/BuildResults/Products/Debug/VulkanTests.xctest/Contents/MacOS/VulkanTests): Library not loaded: @rpath/libvulkan.1.dylib
  Referenced from: /Users/beard/BuildResults/Products/Debug/VulkanTests.xctest/Contents/MacOS/VulkanTests
  Reason: image not found)
Program ended with exit code: 82

They run fine when run from the command line using swift test.

**Comment by pcbeard** [comment] 2021-09-11 23:11
Workaround seems to be to set LD_LIBRARY_PATH to /usr/local/lib in the run arguments.

**Comment by ctreffs** [comment] 2021-11-12 14:10
Can you test this again with https://github.com/ctreffs/SwiftVulkan/releases/tag/0.2.0 ?
I suppose the issue is with ARM support - Homebrew location has changed for ARM based Macs. 
Please verify

**Comment by ctreffs** [comment] 2023-04-21 12:29
Should be fixed with #13

**Closed by ctreffs** 2023-04-21 12:29 UTC
